DROP TABLE IF EXISTS film_likes;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS friendship_status;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
	user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_email varchar NOT NULL,
	user_login varchar NOT NULL,
	user_name varchar NULL,
	user_birthday date NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS friendship_status (
	status_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	status_name varchar NOT NULL,
	CONSTRAINT friendship_status_pk PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS user_friends (
	user_id int4 NOT NULL,
	friend_id int4 NOT NULL,
	status_id int4 NOT NULL,
	CONSTRAINT user_friends_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
	CONSTRAINT user_friends_fk_1 FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE,
	CONSTRAINT user_friends_fk_2 FOREIGN KEY (status_id) REFERENCES friendship_status(status_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mpa (
	mpa_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	mpa_name varchar NOT NULL,
	CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
);

CREATE TABLE IF NOT EXISTS films (
	film_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	film_name varchar NOT NULL,
	film_description varchar NULL,
	film_releaseDate date NOT NULL,
	film_duration int4 NOT NULL,
	film_mpa_id int4 NULL,
	film_rate int4 NULL DEFAULT 0,
	CONSTRAINT films_pk PRIMARY KEY (film_id),
	CONSTRAINT films_fk FOREIGN KEY (film_mpa_id) REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS genres (
	genre_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	genre_name varchar NOT NULL,
	CONSTRAINT category_pk PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
	film_id int4 NOT NULL,
	genre_id int4 NOT NULL,
	CONSTRAINT film_category_fk FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
	CONSTRAINT film_category_fk_1 FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
);

CREATE TABLE film_likes (
	film_id int4 NOT NULL,
	user_id int4 NOT NULL,
	CONSTRAINT film_likes_fk FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
	CONSTRAINT film_likes_fk_1 FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);