DROP TABLE IF EXISTS film_likes, user_friends, film_genres, genres, films, mpa, friendship_status, users, directors, film_directors;

CREATE TABLE IF NOT EXISTS users (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) NOT NULL,
	login varchar(255) NOT NULL,
	name varchar(255) NULL,
	birthday date NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS friendship_status (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	CONSTRAINT friendship_status_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_friends (
	user_id integer NOT NULL,
	friend_id integer NOT NULL,
	status_id integer NOT NULL,
	CONSTRAINT user_friends_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	CONSTRAINT user_friends_fk_1 FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE,
	CONSTRAINT user_friends_fk_2 FOREIGN KEY (status_id) REFERENCES friendship_status(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mpa (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	CONSTRAINT mpa_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	description varchar(255) NULL,
	releaseDate date NOT NULL,
	duration integer NOT NULL,
	mpa_id integer NULL,
	CONSTRAINT films_pk PRIMARY KEY (id),
	CONSTRAINT films_fk FOREIGN KEY (mpa_id) REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS genres (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	CONSTRAINT category_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
	film_id integer NOT NULL,
	genre_id integer NOT NULL,
	CONSTRAINT film_category_fk FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
	CONSTRAINT film_category_fk_1 FOREIGN KEY (genre_id) REFERENCES genres(id)
);

CREATE TABLE film_likes (
	film_id integer REFERENCES films(id),
	user_id integer REFERENCES users(id),
	CONSTRAINT film_likes_pk PRIMARY KEY (film_id,user_id)
);

CREATE TABLE if not exists directors (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_directors (
	film_id integer NOT NULL REFERENCES films(id) ON DELETE CASCADE,
	director_id integer NOT NULL REFERENCES directors(id)  ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);